
import Vue from 'vue'

import vsCol from '@/layout/vsCol/vsCol.vue';
Vue.component(vsCol.name, vsCol);
import vsRow from '@/layout/vsRow/vsRow.vue';
Vue.component(vsRow.name, vsRow);
import vsAlert from '@/components/vsAlert/vsAlert.vue';
Vue.component(vsAlert.name, vsAlert);
import vsDropDown from '@/components/vsDropDown/vsDropDown.vue';
Vue.component(vsDropDown.name, vsDropDown);
import vsDropDownGroup from '@/components/vsDropDown/vsDropDownGroup.vue';
Vue.component(vsDropDownGroup.name, vsDropDownGroup);
import vsDropDownItem from '@/components/vsDropDown/vsDropDownItem.vue';
Vue.component(vsDropDownItem.name, vsDropDownItem);
import vsDropDownMenu from '@/components/vsDropDown/vsDropDownMenu.vue';
Vue.component(vsDropDownMenu.name, vsDropDownMenu);
import vsButton from '@/components/vsButton/vsButton.vue';
Vue.component(vsButton.name, vsButton);
import vsIcon from '@/components/vsIcon/vsIcon.vue';
Vue.component(vsIcon.name, vsIcon);
import vsAvatar from '@/components/vsAvatar/vsAvatar.vue';
Vue.component(vsAvatar.name, vsAvatar);
import vsBreadcrumb from '@/components/vsBreadcrumb/vsBreadcrumb.vue';
Vue.component(vsBreadcrumb.name, vsBreadcrumb);
import vsCard from '@/components/vsCard/vsCard.vue';
Vue.component(vsCard.name, vsCard);
import vsCheckbox from '@/components/vsCheckbox/vsCheckbox.vue';
Vue.component(vsCheckbox.name, vsCheckbox);
import vsChip from '@/components/vsChip/vsChip.vue';
Vue.component(vsChip.name, vsChip);
import vsCollapse from '@/components/vsCollapse/vsCollapse.vue';
Vue.component(vsCollapse.name, vsCollapse);
import vsCollapseItem from '@/components/vsCollapse/vsCollapseItem.vue';
Vue.component(vsCollapseItem.name, vsCollapseItem);
import vsDivider from '@/components/vsDivider/vsDivider.vue';
Vue.component(vsDivider.name, vsDivider);
import vsImage from '@/components/vsImages/vsImage.vue';
Vue.component(vsImage.name, vsImage);
import vsImages from '@/components/vsImages/vsImages.vue';
Vue.component(vsImages.name, vsImages);
import vsInput from '@/components/vsInput/vsInput.vue';
Vue.component(vsInput.name, vsInput);
import vsInputNumber from '@/components/vsInputNumber/vsInputNumber.vue';
Vue.component(vsInputNumber.name, vsInputNumber);
import vsList from '@/components/vsList/vsList.vue';
Vue.component(vsList.name, vsList);
import vsListHeader from '@/components/vsList/vsListHeader.vue';
Vue.component(vsListHeader.name, vsListHeader);
import vsListItem from '@/components/vsList/vsListItem.vue';
Vue.component(vsListItem.name, vsListItem);
import vsNavbar from '@/components/vsNavbar/vsNavbar.vue';
Vue.component(vsNavbar.name, vsNavbar);
import vsNavbarItems from '@/components/vsNavbar/vsNavbarItems.vue';
Vue.component(vsNavbarItems.name, vsNavbarItems);
import vsNavbarTitle from '@/components/vsNavbar/vsNavbarTitle.vue';
Vue.component(vsNavbarTitle.name, vsNavbarTitle);
import vsNavGroup from '@/components/vsNavbar/vsNavGroup.vue';
Vue.component(vsNavGroup.name, vsNavGroup);
import vsNavItem from '@/components/vsNavbar/vsNavItem.vue';
Vue.component(vsNavItem.name, vsNavItem);
import vsPagination from '@/components/vsPagination/vsPagination.vue';
Vue.component(vsPagination.name, vsPagination);
import vsPopup from '@/components/vsPopup/vsPopup.vue';
Vue.component(vsPopup.name, vsPopup);
import vsProgress from '@/components/vsProgress/vsProgress.vue';
Vue.component(vsProgress.name, vsProgress);
import vsRadio from '@/components/vsRadio/vsRadio.vue';
Vue.component(vsRadio.name, vsRadio);
import vsSelect from '@/components/vsSelect/vsSelect.vue';
Vue.component(vsSelect.name, vsSelect);
import vsSelectGroup from '@/components/vsSelect/vsSelectGroup.vue';
Vue.component(vsSelectGroup.name, vsSelectGroup);
import vsSelectItem from '@/components/vsSelect/vsSelectItem.vue';
Vue.component(vsSelectItem.name, vsSelectItem);
import vsTable from '@/components/vsTable/vsTable.vue';
Vue.component(vsTable.name, vsTable);
import vsTd from '@/components/vsTable/vsTd.vue';
Vue.component(vsTd.name, vsTd);
import vsTh from '@/components/vsTable/vsTh.vue';
Vue.component(vsTh.name, vsTh);
import vsTr from '@/components/vsTable/vsTr.vue';
Vue.component(vsTr.name, vsTr);
